# Generated by Django 4.0.4 on 2022-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='knowledge',
            field=models.TextField(max_length=200),
        ),
    ]
