# Generated by Django 4.0.4 on 2022-09-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subjects',
            field=models.TextField(default='-', max_length=255),
        ),
    ]
