# Generated by Django 4.0.4 on 2022-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('date_start', models.DateField(max_length=50)),
                ('time_start', models.TimeField()),
                ('date_end', models.DateField(max_length=50)),
                ('time_end', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
