# Generated by Django 4.0.6 on 2022-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('levels', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('date_stat', models.DateField(max_length=50)),
                ('time_stat', models.TimeField()),
                ('date_end', models.DateField(max_length=50)),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
