# Generated by Django 4.0.6 on 2022-09-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estafetaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='date_stat',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='time_stat',
            new_name='time_start',
        ),
    ]
