# Generated by Django 4.0.4 on 2022-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estafetaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
